### ISSUE TITLE
Can't see the app on the menu bar

### ISSUE THREAD

**Issue by rppig** [wzqcongcong/macSubstrate#1]
there's nothing on the menu bar after launch the app

System version: 10.13
Hardware: MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports)

Additional info:
1. have already disabled SIP
2. I can see macSubstrate's process is running from the activity monitor

**Comment by hging** [comment]
me too

**Comment by rppig** [comment]
It alerts me that macSubstrate is to trying to install a new helper tool every time when I quit the process and relaunch the app. But nothing happened after I entered the password.

**Comment by wzqcongcong** [comment]
I have found the root cause of invisible menu bar on 10.13, and will fix it later. Thanks!

**Comment by wzqcongcong** [comment]
@rppig Please check the following items after launched:
`/Library/macSubstrate/Frameworks/mach_inject_bundle.framework`
`/Library/LaunchDaemons/com.gokustudio.macSubstrateHelper.plist`
`/Library/PrivilegedHelperTools/com.gokustudio.macSubstrateHelper`

Is there a item missed?

**Comment by rppig** [comment]
@wzqcongcong  

```
/Library/macSubstrate/Frameworks/mach_inject_bundle.framework
```
this one is missing.

**Comment by wzqcongcong** [comment]
try the new version

**Comment by wzqcongcong** [comment]
@rppig  try the new version and send me 2 logs if needed:
1. `log show --predicate 'process == "macSubstrate"' > ~/Downloads/macSubstrate.log`
2. /private/var/log/com.gokustudio.macSubstrateHelper.log

**Comment by droid-Q** [comment]
`/Library/macSubstrate/Frameworks/mach_inject_bundle.framework`
this one still is missing.The menu bar doesn't work.
`dyld: Library not loaded: @rpath/mach_inject_bundle.framework/Versions/A/mach_inject_bundle
  Referenced from: /Library/PrivilegedHelperTools/com.gokustudio.macSubstrateHelper
  Reason: image not found`

**Comment by rppig** [comment]
@wzqcongcong it's still not working.

1. it's an empty file
2. 
```
dyld: Library not loaded: @rpath/mach_inject_bundle.framework/Versions/A/mach_inject_bundle
  Referenced from: /Library/PrivilegedHelperTools/com.gokustudio.macSubstrateHelper
  Reason: image not found
```

**Comment by Amosvista** [comment]
nothing on the menu bar😂

**Comment by wzqcongcong** [comment]
https://github.com/wzqcongcong/macSubstrate/releases/tag/1.0.2 should work now.

**Comment by rppig** [comment]
it works now, thanks
