### ISSUE TITLE
SIP

### ISSUE THREAD

**Issue by 0x5e** [wzqcongcong/macSubstrate#2]
之前看到过另一个macOS的微信插件，好像是不用SIP的，当时也想做个类似macSubstrate的东西来着:-)
https://github.com/TKkk-iOSer/WeChatPlugin-MacOS
希望可以帮到你

**Comment by wzqcongcong** [comment]
https://github.com/Tyilo/insert_dylib 和 https://github.com/KJCracks/yololib 这一类方法会去修改原
 app 的 mach-o 文件，原 app 更新后，还得重新搞一遍。不过如果它不需要禁用 SIP 的话，以后会考虑支持这种方式的注入。谢谢。
